---
driver:
  name: ec2
  aws_ssh_key_id: tk-hardhero
  subnet_id: subnet-3227d218
  security_group_ids: ["sg-2e8cc753"]

transport:
 ssh_key: ~/.ssh/tk-hardhero.pem

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[spanning-cookbook::default]
    attributes:
